# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

[[main]]
  name = "Home"
  url = "#"
  weight = 10

[[main]]
  name = "Bio"
  url = "bio/"
  weight = 20

[[main]]
  name = "Practice"
  url = "practice/"
  weight = 30

[[main]]
  name = "What I Teach"
  url = "what-i-teach/"
  weight = 40

[[main]]
  name = "Tuition"
  url = "tuition/"
  weight = 50

[[main]]
  name = "Terms"
  url = "terms/"
  weight = 60

[[main]]
  name = "Special Recognition"
  url = "recognition/"
  weight = 70

[[main]]
  name = "Medal of Honor"
  url = "medal-of-honor/"
  weight = 75

[[main]]
  name = "Contact"
  url = "#contact"
  weight = 80

# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/files/cv.pdf` and uncomment the lines below.
# [[main]]
#    name = "CV"
#    url = "files/cv.pdf"
#    weight = 70
