# SITE SETUP
# Guide: https://wowchemy.com/docs/getting-started/
# Documentation: https://wowchemy.com/docs/
# This file is formatted using YAML syntax - learn more at https://learnxinyminutes.com/docs/yaml/

# Appearance

appearance:
  theme_day: piano
  font: minimal
  font_size: L

# SEO

marketing:
  seo:
    site_type: LocalBusiness
    local_business_type: ProfessionalService
    # org_name: ''
    alternateName: ["Lilia Pershina Piano Studio", "Long Beach Piano Lessons", "Piano Lessons in Long Beach", "Lilia Pershina"]
    description: Discover the best piano lessons in Long Beach, CA with a highly skilled piano instructor. Enroll for beginner to advanced lessons.
    phone: 562-433-4759
    knowsLanguage:
    coordinates:
      latitude: 33.7621668
      longitude: -118.1604354
    address:
      street: 3356 E 1st St D
      city:  Long Beach
      region: CA
      postcode: 90803
      country_code: US
    openingHours: Mo,Tu,We,Th,Fr 12:00-21:00
    paymentAccepted: Cash, Check, Zelle, PayPal, Venmo
    keywords: "piano lessons, long beach, piano lessons long beach, private piano lessons, individual piano lessons, piano"
    hasMap: https://www.google.com/maps?cid=640266995687620706
    sameAs: ["https://www.yelp.com/biz/lilia-pershina-piano-studio-long-beach", "https://www.picklessons.com/213/lilia-pershina", "https://www.google.com/maps?cid=640266995687620706"]
  analytics:
    google_analytics: G-JCFE3FRKPG
    # google_tag_manager: ''
    # baidu_tongji: ''
    # microsoft_clarity: ''
  # verification:
  #   google: ''
  #   baidu: ''

# Site header
header:
  navbar:
    enable: true
    align: l
    show_logo: true
    show_language: false
    show_day_night: false
    show_search: false
    highlight_active_link: true

# Site footer

footer:
  block: minimal
  copyright:
    notice: '© {year} Lilia Pershina'
    license:
      enable: true
      allow_derivatives: false
      share_alike: false
      allow_commercial: false

# Localization

locale:
  date_format: 'Jan 2, 2006'
  time_format: '3:04 PM'
  address_format: en-us

# Site features

features:
  syntax_highlighter:
    enable: false
  math:
    enable: false
  privacy_pack:
    enable: false
  # repository:
  #   url: 'https://github.com/blakskyy/pianolilia.com'
  #   content_dir: content
  #   branch: master
  avatar:
    gravatar: false
    shape: circle
  # search:
  #   provider: wowchemy
  #   algolia:
  #     app_id: ''
  #     api_key: ''
  #     index_name: ''
  #     show_logo: false
  map:
    provider: ''
    api_key: ''
    zoom: 15

# Extensions

extensions:
  cms:
    enable: false
  academicons:
    enable: false

# Security

security:
  # Allow frame for embedding speaker notes in slides
  allow_frame: false
