# SITE SETUP
# Guide: https://wowchemy.com/docs/getting-started/
# Documentation: https://wowchemy.com/docs/
# This file is formatted using YAML syntax - learn more at https://learnxinyminutes.com/docs/yaml/

# Appearance

appearance:
  theme_day: piano
  font: minimal
  font_size: L

# SEO

marketing:
  seo:
    site_type: LocalBusiness
    local_business_type: 'ProfessionalService'
    # org_name: ''
    description: 'Private Piano Lessons in Long Beach for students of any level. The standard piano curriculum taught is based on the proficiency levels set by the California Music Teachers Association.'
    # twitter: ''
  analytics:
    google_analytics: 'G-JCFE3FRKPG'
    # google_tag_manager: ''
    # baidu_tongji: ''
    # microsoft_clarity: ''
  # verification:
  #   google: ''
  #   baidu: ''

# Site header

header:
  navbar:
    enable: true
    align: l
    show_logo: true
    show_language: false
    show_day_night: false
    show_search: false
    highlight_active_link: true

# Site footer

footer:
  block: minimal
  copyright:
    notice: '© {year} Lilia Pershina'
    license:
      enable: true
      allow_derivatives: false
      share_alike: false
      allow_commercial: false

# Localization

locale:
  date_format: 'Jan 2, 2006'
  time_format: '3:04 PM'
  address_format: en-us

# Site features

features:
  syntax_highlighter:
    enable: false
  math:
    enable: false
  privacy_pack:
    enable: false
  # repository:
  #   url: 'https://github.com/blakskyy/pianolilia.com'
  #   content_dir: content
  #   branch: master
  avatar:
    gravatar: false
    shape: circle
  # search:
  #   provider: wowchemy
  #   algolia:
  #     app_id: ''
  #     api_key: ''
  #     index_name: ''
  #     show_logo: false
  map:
    provider: ''
    api_key: ''
    zoom: 15

# Extensions

extensions:
  cms:
    enable: false
  academicons:
    enable: false

# Security

security:
  # Allow frame for embedding speaker notes in slides
  allow_frame: false
